name: C/C++ CI

on:
  push:
    branches: "**"
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
jobs:
    build:
      # name: ${{ matrix.os }}-hosted-basic
      # runs-on: ${{ matrix.os }}
      runs-on: ubuntu-latest
      steps:
      - uses: lukka/get-cmake@latest
      
      - name: Setup
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'a164ace504d8fe6f50aeec7e235d22b9089ad0d5'
      
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: linux-release
          configurePresetAdditionalArgs: "['-DBUILD_EXAMPLE_APP=ON', '-DBUILD_TESTS=ON']"
          buildPreset: linux-release